# GET http://localhost:8888/ping

### GET REQ /USERS
GET http://localhost:8888/users

### POST REQ /USERS
POST http://localhost:8888/users HTTP/1.1
content-type: application/json

{
    "user": "ikujghjgh"
}